# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NxXDsFyUvyhbw_U62yzxsZ3X56eaPvCI
"""

import pandas as pd
url = '/content/student-mat.csv'
df = pd.read_csv(url)
print(df.head())

df.to_csv("output.csv", index=False)

json_data = df.to_json()
df_json = pd.read_json(json_data)
print(df_json.head())

df.to_excel("output.xlsx", index=False)
df_excel = pd.read_excel("output.xlsx")
print(df_excel.head())